### ISSUE TITLE
Blank Bill: A9270-2015

### ISSUE THREAD

**Issue by samsullivan** [nysenate/OpenLegislation#13]
Our technologies stumbled across a "blank" bill.

GET http://legislation.nysenate.gov/api/3/bills/2015/A9270

```
{
  "success" : true,
  "message" : "Data for bill A9270-2015",
  "responseType" : "bill",
  "result" : {
    "basePrintNo" : "A9270",
    "session" : 2015,
    "printNo" : "A9270",
    "billType" : {
      "chamber" : "ASSEMBLY",
      "desc" : "Assembly",
      "resolution" : false
    },
    "title" : "",
    "activeVersion" : "",
    "year" : 2016,
    "publishedDateTime" : "2016-02-10T12:31:30",
    "substitutedBy" : null,
    "sponsor" : null,
    "summary" : "",
    "signed" : false,
    "adopted" : false,
    "vetoed" : false,
    "status" : {
      "statusType" : null,
      "statusDesc" : null,
      "actionDate" : null,
      "committeeName" : null,
      "billCalNo" : null
    },
    "milestones" : {
      "items" : [ ],
      "size" : 0
    },
    "programInfo" : null,
    "amendmentVersions" : {
      "items" : [ ],
      "size" : 0
    },
    "amendments" : {
      "items" : { },
      "size" : 0
    },
    "votes" : {
      "items" : [ ],
      "size" : 0
    },
    "vetoMessages" : {
      "items" : [ ],
      "size" : 0
    },
    "approvalMessage" : null,
    "additionalSponsors" : {
      "items" : [ ],
      "size" : 0
    },
    "pastCommittees" : {
      "items" : [ ],
      "size" : 0
    },
    "actions" : {
      "items" : [ ],
      "size" : 0
    },
    "previousVersions" : {
      "items" : [ ],
      "size" : 0
    },
    "committeeAgendas" : {
      "items" : [ ],
      "size" : 0
    },
    "calendars" : {
      "items" : [ ],
      "size" : 0
    }
  }
}
```

Compare this to an actual missing bill...

GET http://legislation.nysenate.gov/api/3/bills/2015/A9999

```
{
  "success" : false,
  "message" : "The requested bill was not found",
  "responseType" : "error",
  "errorCode" : 11,
  "errorData" : {
    "basePrintNo" : "A9999",
    "session" : 2015,
    "printNo" : "A9999",
    "version" : ""
  },
  "errorDataType" : "bill-id"
}
```

**Comment by samsullivan** [comment]
Okay, this bill has been updated and now I'm seeing the same for J4751-2015. I guess there's just a delay? Not sure if this has always been a thing or maybe I'm just noticing it now...

**Comment by ash858** [comment]
Sorry for the delay and thanks for the summary. The data does come in incrementally but looking at the updates for A9270, it seems like the amendment was also processed upon first receiving that bill, so it shouldn't have been blank. Do you happen to have a timestamp for when you requested this bill and encountered this case?

As for J4751, that resolution has been unpublished, which is why none of the amendments are present. This happens from time to time due to the nature of the data we receive, so it's possible that J4751 may get republished with an amendment at some point.

If there are no amendments present in the JSON, you can assume that the bill/reso is not actively published. Also you can view updates to particular bills by appending /updates (e.g api/3/bills/2015/A9270/updates) in case you want to know how a bill was updated.

**Comment by samsullivan** [comment]
It looks like A9270 first found its way into our system at 2016-02-10 12:34:02 GMT and we first saw the "Referred To Racing And Wagering" activity at 2016-02-11 09:34:21 GMT.

I'll take a look at the /updates endpoint when I get a moment -- thanks!

**Comment by kzalewski** [comment]
Those "blank bill" issues have been resolved.

This issue is closed.
