### ISSUE TITLE
Delay between API and Assembly Website

### ISSUE THREAD

**Issue by phaskins** [nysenate/OpenLegislation#37]
Hello. I noticed today that there seems to be quite a few new bills located on the Assembly website that aren't yet available in the API (for ex: AB8739, AB8823, AB8832, AB8810, AB8762, AB8765, AB8772, AB8807, AB8829, AB8734), as well as some updated actions for existing bills. Will these be available in the API soon and can we expect a continual 1-day delay or so between the website and the API?

Thanks!

**Comment by KevinCaseiras** [comment]
@phaskins Thanks for notifying us of this issue. It appears our application encountered some issues and was not properly processing data. Everything is up and running now and those bills are available in our api (Assuming you mean `A08739` instead of `AB8739`, etc). Usually our API is only delayed by a few minutes.

**Comment by phaskins** [comment]
@KevinCaseiras Ah right, that's what I meant. Thank you very much!
