### ISSUE TITLE
question about the completeness of the data

### ISSUE THREAD

**Issue by fedex1** [nysenate/OpenLegislation#4]
Hi

Thanks for open.nysenate.gov!

We are trying to understand how much of the New York State history is in this database.

It appears that the oldest documents by type are:

* transcript - 1993 see [link] (http://open.nysenate.gov/legislation/2.0/search.jsonp?pageSize=1&pageIdx=1&sort=modified&sortOrder=false&term=otype%3Atranscript&callback=a)
* bill - 2009 see [link] (http://open.nysenate.gov/legislation/2.0/search.jsonp?pageSize=1&pageIdx=1&sort=modified&sortOrder=false&term=otype%3Abill&callback=a)
* action - 2007 see [link] (http://open.nysenate.gov/legislation/2.0/search.jsonp?pageSize=1&pageIdx=1&sort=modified&sortOrder=false&term=otype%3Aaction&callback=a)

We definitely appreciate the data that exists.
Our questions are:

* Are these oldest document dates correct?
* If so, are there plans to add the older data.  For example, all the bills and actions must be stored somewhere and would be helpful for analysis and for history.
* Also, (assuming the dates are correct) why do transcripts go back to 1993 and bills only back to 2009?

**Comment by kzalewski** [comment]
Hi Ralph,

Thank you for recognizing our efforts on OpenLegislation.

To answer your questions:

1. Yes, the oldest transcript is from 1993, while the oldest bill is from 2009.  The bill action from 2007 is a fluke.  Somehow, we have a single bill from 2007 that slipped in.

2. Yes, we would like to add older data.  LBDC (the Legislative Bill Drafting Commission) is the maintainer of the canonical repository of bill data in New York State.  Both the Senate and the Assembly receive data from LBDC in order to populate our own legislative applications.  I'll detail some of this in #3 below.

3. Transcripts are sent to the Senate directly from the stenographer.  They do not originate from LBDC.  The oldest transcript that we have is from 1993.  Bill data, as I mentioned in #2, is sent to us from LBDC.  The oldest bill on the Assembly's website is from 1999, while the oldest bill on the Senate's OpenLegislation website is from 2009.  This is because the Assembly's home-grown bill search application went online in 1999, while the Senate's app went live in 2009.  Each house receives live bill data from LBDC, parses that data, stores it in a database, and makes it available via a web interface and/or an API.

You can view bill data all the way back to 1995 on LBDC's bill search site, which is at:
http://public.leginfo.state.ny.us/

We would definitely like to populate our OpenLegislation service with historical bill data (pre-2009), and will discuss this with LBDC in the near future.

Let me know if this answers your questions.

**Comment by fedex1** [comment]
Hi Ken,

Thank you very much.  And yes this does answer the questions.

It appears that at http://public.leginfo.state.ny.us/ you cannot search across all years and cannot list the bills and there seems to be no API.

Please yes, if we could all urge all the data to be in the searchable database and available via an API that would be much better.

Thanks for your answers.
