### ISSUE TITLE
Feature Request: Law search support in API

### ISSUE THREAD

**Issue by fedex1** [nysenate/OpenLegislation#6]
Is there a way to search the actual current NYS law in the lucene search api?

For example we'd like an otype = law 

See http://openlegislation.readthedocs.org/en/latest/

It would be very helpful.

The current http://public.leginfo.state.ny.us/lawssrch.cgi?NVLWO: site search is very limited.

In fact, it appears to be difficult to even link to this http://public.leginfo.state.ny.us/lawssrch.cgi?NVLWO: site for specific sections or search results.

For example, try to share a link to section 1236 of the NYS VAT law and it seems to be difficult.

The user would have to know the internals of the site.

We suggest to add a "share link" to the http://public.leginfo.state.ny.us site

For every search, show the user the equivalent share link.  For example for Section 1236 of VAT the link would be: 

(This is simply the POST parameters changed to GET parameters.)

> http://public.leginfo.state.ny.us/lawssrch.cgi?NVLWO:?SITECHGNO=&SITEBFPAGE=&SEATYPE=AQUA&QLAWDATA=%24%24VAT1236%24%24%40TXVAT01236&LIST=SEA3&hwebpage=LAWS&haction=&ZQLAWDATA=1236&HQLAWDATA=1236&FRMT=+&HILITE=+&hsearesults=N&hseareq=Y&hcontents=N&hcontreq=N&PHREFLW=&PHREFNO=&PHREFNM=&NHREFLW=%24%24VAT375%24%24%40TXVAT0375&NHREFNO=SEA2&NHREFNM=Vehicle+and+Traffic+Law+%C2%A7+375&HTOKEN=15912673&hdlnkrows=0000&hdlinkstbl=&hsessyr=0000&CBSTATUS=&CBTEXT=&CBSUMMARY=&CBSPONMEMO=&CBUNFORMATTED=&CBBILLFILE=&CBBILLTRK=&CBBLIQ=&CBFACESHEET=&CBGOVPOSN=&CBMAYORPOSN=&CBBILLTITLE=&CBASMHR=&CBSENHR=&CBCBR=&CBSAHIST=&CBACTRULES=

There seems to be yet another government site that lists all the NYS LAWS that seems to be better designed and we can link to specific sections of law see http://www.safeny.ny.gov/bike-vt.htm#sec1236

But the safeny.ny.gov site specifically says it is not an authority.

```
	PLEASE READ THIS FIRST!
These excerpts are provided for information only and NOT as the basis for legal or judicial determinations.  ALWAYS verify them against the most recent available copy of the law.  The entire Vehicle and Traffic Law, sorted by section number, is available from the New York State Legislative Bill Drafting Commission. (scroll down to VAT) external link
```

Here's one example of the HTTP POST required to search:

> curl 'http://public.leginfo.state.ny.us/lawssrch.cgi?NVLWO:' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: max-age=0' -H 'Referer: http://public.leginfo.state.ny.us/lawssrch.cgi?NVLWO:' -H 'Connection: keep-alive' --data 'SITECHGNO=&SITEBFPAGE=&SEATYPE=AQUA&QLAWDATA=FINE+RED+SIGNAL&LIST=SEA1&hwebpage=SEARCH&haction=&ZQLAWDATA=FINE+RED+SIGNAL&HQLAWDATA=FINE+RED+SIGNAL&FRMT=+&HILITE=+&hsearesults=N&hseareq=Y&hcontents=N&hcontreq=N&PHREFLW=&PHREFNO=&PHREFNM=&NHREFLW=%40PLADC0T29C2&NHREFNO=SEA2&NHREFNM=New+York+City+Administrative+Code+%C2%A7+T29C2&HTOKEN=15912673&hdlnkrows=0000&hdlinkstbl=&hsessyr=0000&CBSTATUS=&CBTEXT=&CBSUMMARY=&CBSPONMEMO=&CBUNFORMATTED=&CBBILLFILE=&CBBILLTRK=&CBBLIQ=&CBFACESHEET=&CBGOVPOSN=&CBMAYORPOSN=&CBBILLTITLE=&CBASMHR=&CBSENHR=&CBCBR=&CBSAHIST=&CBACTRULES=' --compressed

Here is the same HTTP POST on one line:
```
curl 'http://public.leginfo.state.ny.us/lawssrch.cgi?NVLWO:' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: max-age=0' -H 'Referer: http://public.leginfo.state.ny.us/lawssrch.cgi?NVLWO:' -H 'Connection: keep-alive' --data 'SITECHGNO=&SITEBFPAGE=&SEATYPE=AQUA&QLAWDATA=FINE+RED+SIGNAL&LIST=SEA1&hwebpage=SEARCH&haction=&ZQLAWDATA=FINE+RED+SIGNAL&HQLAWDATA=FINE+RED+SIGNAL&FRMT=+&HILITE=+&hsearesults=N&hseareq=Y&hcontents=N&hcontreq=N&PHREFLW=&PHREFNO=&PHREFNM=&NHREFLW=%40PLADC0T29C2&NHREFNO=SEA2&NHREFNM=New+York+City+Administrative+Code+%C2%A7+T29C2&HTOKEN=15912673&hdlnkrows=0000&hdlinkstbl=&hsessyr=0000&CBSTATUS=&CBTEXT=&CBSUMMARY=&CBSPONMEMO=&CBUNFORMATTED=&CBBILLFILE=&CBBILLTRK=&CBBLIQ=&CBFACESHEET=&CBGOVPOSN=&CBMAYORPOSN=&CBBILLTITLE=&CBASMHR=&CBSENHR=&CBCBR=&CBSAHIST=&CBACTRULES=' --compressed
```

**Comment by ash858** [comment]
Hi there,

First just for some clarification, the http://public.leginfo.state.ny.us/lawssrch.cgi?NVLWO:  site is not maintained by the Senate, but rather the Legislative Bill Drafting Commission. Making direct changes to the leginfo site (e.g. adding a share button) is outside the scope of this project. 

The good news is that the Senate has been receiving direct law updates from the bill drafting commission since September of last year. This data is only available through our recent beta version of OpenLeg which is deployed for testing here: http://openleg-dev.nysenate.gov/ (only current browsers are supported).

If you are interested in using the API to retrieve laws, sign up for a key on the home page of that site, (You will need to append your key as a query param to api calls: ?key=YOUR_KEY) and visit the law api docs (which are a work in progress): https://github.com/nysenate/OpenLegislation/blob/master/docs/laws.rst

Some of the metadata parsing for laws is incomplete but the text of each law document should be accurate (it's updated weekly). We'd appreciate it if you informed us about any issues you encounter so we can further refine the next release of this service.

Hope this helps,
Ash

**Comment by ash858** [comment]
Also, I'll update the docs to demonstrate how to perform full text law searches using the API shortly.
